steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.prod', '-t', 'us-east4-docker.pkg.dev/musicuploadservice/python-fastapi-sample/python-fastapi:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east4-docker.pkg.dev/musicuploadservice/python-fastapi-sample/python-fastapi:latest']